name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install Lint
        run: npm install eslint-plugin-react @eslint/js --save-dev
      - name: install babel
        run: npm install @babel/eslint-parser --save-dev
      - name: install preset
        run: npm install @babel/preset-react --save-dev
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."